function [dfhat] = MultifhatDerivs(f,df,V,dV)
%MULTIFHATDERIVS finds the derivative of fhat at multiple times.

%Choose Dimensions.
Dim=size(f);
%Preallocate dfhat.
dfhat=cell(Dim);
%Transform f. (f=V*fhat*V^T)
if isequal(Dim,[2,2])
    for i=1:2
        %Symmetry speed up.
        for k=1:i-1
            dfhat{i,k}=dfhat{k,i};
        end
        %Transform. (Note that cell i,k are cartesian, matrix dims are s,s',t)
        for k=i:2
            dVfV=dV(1,i,:).*V(1,k,:).*f{1,1}+...
                dV(2,i,:).*V(2,k,:).*f{2,2}+...
                ((dV(1,i,:).*V(2,k,:))+(dV(2,i,:).*V(1,k,:))).*f{1,2};
            VfdV=V(1,i,:).*dV(1,k,:).*f{1,1}+...
                V(2,i,:).*dV(2,k,:).*f{2,2}+...
                ((V(1,i,:).*dV(2,k,:))+(V(2,i,:).*dV(1,k,:))).*f{1,2};
            VdfV=V(1,i,:).*V(1,k,:).*df{1,1}+...
                V(2,i,:).*V(2,k,:).*df{2,2}+...
                ((V(1,i,:).*V(2,k,:))+(V(2,i,:).*V(1,k,:))).*df{1,2};
            dfhat{i,k}=dVfV+VfdV+VdfV;
        end
    end
elseif isequal(Dim,[3,3])
    for i=1:3
        %Symmetry speed up.
        for k=1:i-1
            dfhat{i,k}=dfhat{k,i};
        end
        %Transform. (Note that cell i,k are cartesian, matrix dims are s,s',t)
        for k=i:3
            dVfV=dV(1,i,:).*V(1,k,:).*f{1,1}+...
                dV(2,i,:).*V(2,k,:).*f{2,2}+...
                dV(3,i,:).*V(3,k,:).*f{3,3}+...
                ((dV(1,i,:).*V(2,k,:))+(dV(2,i,:).*V(1,k,:))).*f{1,2}+...
                ((dV(1,i,:).*V(3,k,:))+(dV(3,i,:).*V(1,k,:))).*f{1,3}+...
                ((dV(2,i,:).*V(3,k,:))+(dV(3,i,:).*V(2,k,:))).*f{2,3};
            VfdV=V(1,i,:).*dV(1,k,:).*f{1,1}+...
                V(2,i,:).*dV(2,k,:).*f{2,2}+...
                V(3,i,:).*dV(3,k,:).*f{3,3}+...
                ((V(1,i,:).*dV(2,k,:))+(V(2,i,:).*dV(1,k,:))).*f{1,2}+...
                ((V(1,i,:).*dV(3,k,:))+(V(3,i,:).*dV(1,k,:))).*f{1,3}+...
                ((V(2,i,:).*dV(3,k,:))+(V(3,i,:).*dV(2,k,:))).*f{2,3};
            VdfV=V(1,i,:).*V(1,k,:).*df{1,1}+...
                V(2,i,:).*V(2,k,:).*df{2,2}+...
                V(3,i,:).*V(3,k,:).*df{3,3}+...
                ((V(1,i,:).*V(2,k,:))+(V(2,i,:).*V(1,k,:))).*df{1,2}+...
                ((V(1,i,:).*V(3,k,:))+(V(3,i,:).*V(1,k,:))).*df{1,3}+...
                ((V(2,i,:).*V(3,k,:))+(V(3,i,:).*V(2,k,:))).*df{2,3};
            dfhat{i,k}=dVfV+VfdV+VdfV;
        end
    end
else
    error('Incorrect dimensions of f.')
end
end